swiftmailer:
    transport: smtp
    encryption: ssl
    auth_mode: login
    port: 465
    host: ssl0.ovh.net
    username: ne-pas-repondre@diversis.fr
    password: YEXFGUn2IBHEYBIM2R2rmE1r8jKX1e
    spool: { type: 'memory' }